### PR TITLE
Allow mixing operators

### LINKED ISSUE #3: Allow mixing operators?
http://www.reddit.com/r/haskell/comments/324415/write_more_understandable_haskell_with_flow/cq8mehu

```
>>> x |> f <| y

<interactive>:1:1:
    Precedence parsing error
        cannot mix ‘|>’ [infixl 0] and ‘<|’ [infixr 0] in the same infix expression
```

I think it's reasonable to treat `x |> f <| y` as `(x |> f) <| y`.

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #3.

### CODE REVIEW

**Comment by tfausak** [comment]
One problem with this approach is that `<|` doesn't behave like you might expect.

``` hs
f x y z
x |> f <| y <| z -- Wrong!
```

Since `<|` is meant to represent right-to-left pipelines, it doesn't work well with multiple arguments.

``` hs
h (g (f x))
h <| g <| f <| x
```

**Comment by tfausak** [comment]
@tonyday567 are you interested in this pull request?

**Comment by tonyday567** [comment]
Hi tf,
I see what you mean, but I don't work well with multiple arguments either ;)

I'd say that this precedence is marginally better, but don't consider my opinion well-thought.

**Comment by tfausak** [comment]
I agree that it's marginally better. I'm not sure if it's worth adding this or not.

**Comment by tonyday567** [comment]
Leave it out then, IMO.  I think the best path for this library is to maintain design clarity, and be ruthless about scope creep.

**Comment by tfausak** [comment]
:+1: I think that's a good goal for any library.

**Pull request closed without merging**
